function AU_table(varargin)
% AU_TABLE  Prints a formatted reference table of atomic unit conversion
%           factors (CODATA 2022).
%
%   AU_TABLE            — print full table to console
%   AU_TABLE('energy')  — print only the energy section
%   AU_TABLE('length')  — print only the length section
%   (etc. — section names match AU_convert quantity strings)
%
%   All factors are from CODATA 2022 (NIST, November 2024 release).

filter = '';
if nargin > 0 && ischar(varargin{1})
    filter = lower(strtrim(varargin{1}));
end

% ── Fundamental constants (CODATA 2022) ───────────────────────────────────
e    = 1.602176634e-19;
me   = 9.1093837139e-31;
mp   = 1.67262192595e-27;
hbar = 1.054571817e-34;
h    = 6.62607015e-34;
c    = 299792458.0;
kB   = 1.380649e-23;
NA   = 6.02214076e23;
a0   = 5.29177210544e-11;
Eh   = 4.3597447222060e-18;
eps0 = 8.8541878188e-12;

% Derived
alpha_au = e^2 * a0^2 / Eh;
beta_au  = e^3 * a0^3 / Eh^2;
gamma_au = e^4 * a0^4 / Eh^3;

% ── Section definitions ────────────────────────────────────────────────────
sections = {};

sections{end+1} = struct( ...
    'title', 'FUNDAMENTAL CONSTANTS  (CODATA 2022)', ...
    'tag',   'constants', ...
    'rows',  {{ ...
        'Bohr radius  a0',        sprintf('%.10e m',  a0); ...
        'Hartree  Eh',            sprintf('%.10e J',  Eh); ...
        'Electron mass  me',      sprintf('%.10e kg', me); ...
        'Proton mass  mp',        sprintf('%.10e kg', mp); ...
        'Elementary charge  e',   sprintf('%.10e C',  e); ...
        'Planck const  h',        sprintf('%.10e J·s', h); ...
        'Reduced Planck  ħ',      sprintf('%.10e J·s', hbar); ...
        'Speed of light  c',      sprintf('%d m/s (exact)', c); ...
        'Boltzmann  kB',          sprintf('%.10e J/K (exact)', kB); ...
        'Avogadro  NA',           sprintf('%.10e mol⁻¹ (exact)', NA); ...
        'Vacuum permittivity ε0', sprintf('%.10e F/m', eps0); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'ENERGY', ...
    'tag',   'energy', ...
    'rows',  {{ ...
        '1 Hartree (Eh)',   sprintf('= %.10e J',        Eh); ...
        '',                  sprintf('= %.6f kJ/mol',    Eh*NA/1000); ...
        '',                  sprintf('= %.6f kcal/mol',  Eh*NA/4184); ...
        '',                  sprintf('= %.6f eV',        Eh/e); ...
        '',                  sprintf('= %.4f cm⁻¹',     Eh/(h*c*100)); ...
        '',                  sprintf('= %.6f meV',       Eh/e*1000); ...
        '1 eV',              sprintf('= %.10e J',        e); ...
        '',                  sprintf('= %.4f kJ/mol',    e*NA/1000); ...
        '',                  sprintf('= %.4f cm⁻¹',     e/(h*c*100)); ...
        '1 cm⁻¹',           sprintf('= %.10e J',        h*c*100); ...
        '',                  sprintf('= %.8e Hartree',  h*c*100/Eh); ...
        '1 kJ/mol',          sprintf('= %.8e Hartree',  1000/(Eh*NA)); ...
        '1 kcal/mol',        sprintf('= %.8e Hartree',  4184/(Eh*NA)); ...
        '1 kBT (298.15K)',   sprintf('= %.8e Hartree  (= %.4f kJ/mol)', kB*298.15/Eh, kB*298.15*NA/1000); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'LENGTH', ...
    'tag',   'length', ...
    'rows',  {{ ...
        '1 Bohr (a0)',  sprintf('= %.10e m',         a0); ...
        '',              sprintf('= %.10f Å',          a0*1e10); ...
        '',              sprintf('= %.6f pm',           a0*1e12); ...
        '1 Å',          sprintf('= %.10f Bohr',        1e-10/a0); ...
        '1 pm',         sprintf('= %.10f Bohr',        1e-12/a0); ...
        '1 nm',         sprintf('= %.6f Bohr',         1e-9/a0); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'DIPOLE MOMENT', ...
    'tag',   'dipole', ...
    'rows',  {{ ...
        '1 au  (e·a0)',  sprintf('= %.10e C·m',      e*a0); ...
        '',               sprintf('= %.8f Debye',     e*a0/3.33564095e-30); ...
        '1 Debye',        sprintf('= %.10e C·m',     3.33564095e-30); ...
        '',               sprintf('= %.8f au',        3.33564095e-30/(e*a0)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'POLARISABILITY  α', ...
    'tag',   'polar', ...
    'rows',  {{ ...
        '1 au  (e²a0²/Eh)',  sprintf('= %.10e C²·m²·J⁻¹',  alpha_au); ...
        '',                   sprintf('= %.6f Å³  (volume)',  alpha_au/(4*pi*eps0)*1e30); ...
        '',                   sprintf('= %.6e cm³  (esu)',   alpha_au/(4*pi*eps0)*1e6); ...
        '1 Å³',              sprintf('= %.6f au',            (4*pi*eps0)*1e-30/alpha_au); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'FIRST HYPERPOLARISABILITY  β', ...
    'tag',   'beta', ...
    'rows',  {{ ...
        '1 au  (e³a0³/Eh²)',  sprintf('= %.6e C³·m³·J⁻²  (SI)',  beta_au); ...
        '',                    sprintf('= %.6e esu  (×10⁻³³)',     8.6392e-33); ...
        '1 ×10⁻³³ esu',       sprintf('= %.6f au',               1e-33/8.6392e-33); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'SECOND HYPERPOLARISABILITY  γ', ...
    'tag',   'gamma', ...
    'rows',  {{ ...
        '1 au  (e⁴a0⁴/Eh³)',  sprintf('= %.6e C⁴·m⁴·J⁻³  (SI)',  gamma_au); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'FORCE', ...
    'tag',   'force', ...
    'rows',  {{ ...
        '1 au  (Eh/a0)',  sprintf('= %.6e N',   Eh/a0); ...
        '',               sprintf('= %.6f nN',  Eh/a0*1e9); ...
        '1 nN',           sprintf('= %.8f au',  1e-9/(Eh/a0)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'FORCE CONSTANT', ...
    'tag',   'frcconst', ...
    'rows',  {{ ...
        '1 au  (Eh/a0²)',  sprintf('= %.4f N/m',      Eh/a0^2); ...
        '',                 sprintf('= %.4f mDyne/Å',   Eh/a0^2*1e-2); ...
        '1 mDyne/Å',       sprintf('= %.8f au',         1e-2/(Eh/a0^2)); ...
        '1 N/m',           sprintf('= %.8f au',          1/(Eh/a0^2)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'FREQUENCY', ...
    'tag',   'frequency', ...
    'rows',  {{ ...
        '1 au  (Eh/ħ)',  sprintf('= %.6e rad/s',   Eh/hbar); ...
        '',               sprintf('= %.6e Hz',       Eh/(hbar*2*pi)); ...
        '',               sprintf('= %.4f cm⁻¹',    Eh/(hbar*2*pi*c*100)); ...
        '',               sprintf('= %.4f THz',      Eh/(hbar*2*pi*1e12)); ...
        '1 cm⁻¹',        sprintf('= %.10e au',     h*c*100/Eh); ...
        '1 THz',         sprintf('= %.10e au',      1e12*2*pi*hbar/Eh); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'TIME', ...
    'tag',   'time', ...
    'rows',  {{ ...
        '1 au  (ħ/Eh)',  sprintf('= %.6e s',        hbar/Eh); ...
        '',               sprintf('= %.6f as  (attoseconds)', hbar/Eh*1e18); ...
        '',               sprintf('= %.6e fs',       hbar/Eh*1e15); ...
        '1 fs',          sprintf('= %.4f au',        1e-15/(hbar/Eh)); ...
        '1 as',          sprintf('= %.6f au',        1e-18/(hbar/Eh)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'PRESSURE', ...
    'tag',   'pressure', ...
    'rows',  {{ ...
        '1 au  (Eh/a0³)',  sprintf('= %.6e Pa',    Eh/a0^3); ...
        '',                 sprintf('= %.4f GPa',   Eh/a0^3/1e9); ...
        '',                 sprintf('= %.4e atm',   Eh/a0^3/101325); ...
        '1 GPa',           sprintf('= %.6e au',    1e9/(Eh/a0^3)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'ELECTRIC FIELD', ...
    'tag',   'efield', ...
    'rows',  {{ ...
        '1 au  (Eh/ea0)',  sprintf('= %.6e V/m',   Eh/(e*a0)); ...
        '',                 sprintf('= %.4f GV/m',  Eh/(e*a0)/1e9); ...
        '',                 sprintf('= %.4f V/Å',   Eh/(e*a0)*1e-10); ...
        '1 V/Å',           sprintf('= %.6e au',    1e10*e*a0/Eh); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'MASS', ...
    'tag',   'mass', ...
    'rows',  {{ ...
        '1 au  (me)',  sprintf('= %.10e kg',          me); ...
        '',             sprintf('= %.8e Da (AMU)',     me/1.66053906892e-27); ...
        '1 Da (AMU)',  sprintf('= %.4f au  (me)',      1.66053906892e-27/me); ...
        '1 mp',        sprintf('= %.4f au  (me)',      mp/me); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'CHARGE', ...
    'tag',   'charge', ...
    'rows',  {{ ...
        '1 au  (e)',  sprintf('= %.10e C  (elementary charge)', e); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'MAGNETIC MOMENT', ...
    'tag',   'magmom', ...
    'rows',  {{ ...
        '1 au  (μB)',  sprintf('= %.10e J/T  (Bohr magneton)', e*hbar/(2*me)); ...
        '1 μN',        sprintf('= %.6e J/T  (nuclear magneton)', e*hbar/(2*mp)); ...
    }} ...
);

sections{end+1} = struct( ...
    'title', 'TEMPERATURE  (via thermal energy)', ...
    'tag',   'temp', ...
    'rows',  {{ ...
        '1 Eh = kBT  ↔  T',  sprintf('= %.4f K', Eh/kB); ...
        '1 K  ↔  kBT',       sprintf('= %.6e Eh', kB/Eh); ...
        'kBT at 298.15 K',   sprintf('= %.6e Eh  = %.4f meV', kB*298.15/Eh, kB*298.15/e*1000); ...
    }} ...
);

% ── Print ──────────────────────────────────────────────────────────────────
fprintf('\n');
fprintf('══════════════════════════════════════════════════════════════════\n');
fprintf('  AU_TABLE — Atomic Unit Conversion Reference  (CODATA 2022)\n');
fprintf('  Sebastiano Trusso · CNR-IPCF Messina  ·  Claude Sonnet 4.6\n');
fprintf('══════════════════════════════════════════════════════════════════\n');

for si = 1:numel(sections)
    sec = sections{si};
    if ~isempty(filter) && ~strcmpi(filter, sec.tag) && ~strcmpi(filter, 'all')
        continue
    end
    fprintf('\n  ── %s ──\n', sec.title);
    for ri = 1:size(sec.rows, 1)
        lbl = sec.rows{ri, 1};
        val = sec.rows{ri, 2};
        if isempty(lbl)
            fprintf('  %28s  %s\n', '', val);
        else
            fprintf('  %-28s  %s\n', lbl, val);
        end
    end
end

fprintf('\n  For conversions: AU_convert(value, quantity, ''au2si''|''si2au'', ''target'', unit)\n');
fprintf('  For help:        AU_convert([], ''help'', '''')\n\n');

end  % AU_table